#  Based on janekb04's Deep Dark theme, at <https://github.com/ocornut/imgui/issues/707#issuecomment-917151020>

Color_Text                   = [1.00, 1.00, 1.00, 1.00]
Color_TextDisabled           = [0.50, 0.50, 0.50, 1.00]
Color_WindowBg               = [0.10, 0.10, 0.10, 1.00]
Color_ChildBg                = [0.00, 0.00, 0.00, 0.00]
Color_PopupBg                = [0.19, 0.19, 0.19, 0.92]
Color_Border                 = [0.19, 0.19, 0.19, 0.29]
Color_BorderShadow           = [0.00, 0.00, 0.00, 0.24]
Color_FrameBg                = [0.05, 0.05, 0.05, 0.54]
Color_FrameBgHovered         = [0.19, 0.19, 0.19, 0.54]
Color_FrameBgActive          = [0.20, 0.22, 0.23, 1.00]
Color_TitleBg                = [0.00, 0.00, 0.00, 1.00]
Color_TitleBgActive          = [0.06, 0.06, 0.06, 1.00]
Color_TitleBgCollapsed       = [0.00, 0.00, 0.00, 1.00]
Color_MenuBarBg              = [0.14, 0.14, 0.14, 1.00]
Color_ScrollbarBg            = [0.05, 0.05, 0.05, 0.54]
Color_ScrollbarGrab          = [0.34, 0.34, 0.34, 0.54]
Color_ScrollbarGrabHovered   = [0.40, 0.40, 0.40, 0.54]
Color_ScrollbarGrabActive    = [0.56, 0.56, 0.56, 0.54]
Color_CheckMark              = [0.33, 0.67, 0.86, 1.00]
Color_SliderGrab             = [0.34, 0.34, 0.34, 0.54]
Color_SliderGrabActive       = [0.56, 0.56, 0.56, 0.54]
Color_Button                 = [0.05, 0.05, 0.05, 0.54]
Color_ButtonHovered          = [0.19, 0.19, 0.19, 0.54]
Color_ButtonActive           = [0.20, 0.22, 0.23, 1.00]
Color_Header                 = [0.00, 0.00, 0.00, 0.52]
Color_HeaderHovered          = [0.00, 0.00, 0.00, 0.36]
Color_HeaderActive           = [0.20, 0.22, 0.23, 0.33]
Color_Separator              = [0.28, 0.28, 0.28, 0.29]
Color_SeparatorHovered       = [0.44, 0.44, 0.44, 0.29]
Color_SeparatorActive        = [0.40, 0.44, 0.47, 1.00]
Color_ResizeGrip             = [0.28, 0.28, 0.28, 0.29]
Color_ResizeGripHovered      = [0.44, 0.44, 0.44, 0.29]
Color_ResizeGripActive       = [0.40, 0.44, 0.47, 1.00]
Color_Tab                    = [0.00, 0.00, 0.00, 0.52]
Color_TabHovered             = [0.14, 0.14, 0.14, 1.00]
Color_TabActive              = [0.20, 0.20, 0.20, 0.36]
Color_TabUnfocused           = [0.00, 0.00, 0.00, 0.52]
Color_TabUnfocusedActive     = [0.14, 0.14, 0.14, 1.00]
Color_DockingPreview         = [0.33, 0.67, 0.86, 1.00]
Color_DockingEmptyBg         = [1.00, 0.00, 0.00, 1.00]
Color_PlotLines              = [1.00, 0.00, 0.00, 1.00]
Color_PlotLinesHovered       = [1.00, 0.00, 0.00, 1.00]
Color_PlotHistogram          = [1.00, 0.00, 0.00, 1.00]
Color_PlotHistogramHovered   = [1.00, 0.00, 0.00, 1.00]
Color_TableHeaderBg          = [0.00, 0.00, 0.00, 0.52]
Color_TableBorderStrong      = [0.00, 0.00, 0.00, 0.52]
Color_TableBorderLight       = [0.28, 0.28, 0.28, 0.29]
Color_TableRowBg             = [0.00, 0.00, 0.00, 0.00]
Color_TableRowBgAlt          = [1.00, 1.00, 1.00, 0.06]
Color_TextSelectedBg         = [0.20, 0.22, 0.23, 1.00]
Color_DragDropTarget         = [0.33, 0.67, 0.86, 1.00]
Color_NavHighlight           = [1.00, 0.00, 0.00, 1.00]
Color_NavWindowingHighlight  = [1.00, 0.00, 0.00, 0.70]
Color_NavWindowingDimBg      = [1.00, 0.00, 0.00, 0.20]
Color_ModalWindowDimBg       = [1.00, 0.00, 0.00, 0.35]

Style_WindowPadding             = [8.00, 8.00]
Style_FramePadding              = [5.00, 2.00]
Style_CellPadding               = [6.00, 6.00]
Style_ItemSpacing               = [6.00, 6.00]
Style_ItemInnerSpacing          = [6.00, 6.00]
Style_TouchExtraPadding         = [0.00, 0.00]
Style_IndentSpacing             = 25
Style_ScrollbarSize             = 15
Style_GrabMinSize               = 10
Style_WindowBorderSize          = 1
Style_ChildBorderSize           = 1
Style_PopupBorderSize           = 1
Style_FrameBorderSize           = 1
Style_TabBorderSize             = 1
Style_WindowRounding            = 7
Style_ChildRounding             = 4
Style_FrameRounding             = 3
Style_PopupRounding             = 4
Style_ScrollbarRounding         = 9
Style_GrabRounding              = 3
Style_LogSliderDeadzone         = 4
Style_TabRounding               = 4
